apiVersion: v1
kind: Service

metadata:
  name: shopping-backend-service
  namespace: shopping

spec:
  type: ClusterIP

  selector:
    app: shopping-backend

  ports:
    - port: 5000
      targetPort: 5000