apiVersion: v1
kind: Service

metadata:
  name: shopping-frontend-service
  namespace: shopping

spec:
  type: LoadBalancer

  selector:
    app: shopping-frontend

  ports:
    - port: 80
      targetPort: 80